name: Build
on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # TODO: enable other platforms once I verify the app/build works
        # runs-on: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: [windows-latest]
        python-version: ["3.11"]
        poetry-version: ["1.8.3"]
    runs-on: ${{ matrix.runs-on }}
    outputs:
      app-version: ${{ steps.get-version.outputs.APP_VERSION }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install PyInstaller plugin
        run: poetry self add poetry-pyinstaller-plugin
      - name: Install dependencies
        run: poetry install
      - name: Build app
        run: poetry build
      - name: Run tests
        if: false # TODO: Enable once tests are set up
        run: poetry run pytest -v
      - name: Get version
        id: get-version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "::set-output name=APP_VERSION::$(poetry version -s)"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: yt-dlp-guitk_${{ steps.get-version-step.outputs.APP_VERSION }}_${{ matrix.runs-on }}
          # TODO: Handle filename for other platforms when enabling them
          path: dist/pyinstaller/*/yt-dlp-guitk/yt-dlp-guitk.exe
  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        id: download-artifacts
        uses: actions/download-artifact@v4
        with:
          path: yt-dlp-guitk
          pattern: yt-dlp-guitk_*
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.download-artifacts.outputs.download-path }}/*
          token: ${{ secrets.GITHUB_TOKEN }}pe
